name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Checkov installation
      uses: actions/cache@v2
      with:
       path: ~/.terraform.d/plugins/checkov # path to Checkov installation directory
       key: ${{ runner.os }}-checkov
       restore-keys: ${{ runner.os }}-checkov-
    - name: Install Checkov
      run: |
          pip install checkov
