name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dir-create
      run: |
        mkdir -p ~/.terraform.d/plugins/checkov
    - uses: actions/cache/restore@v3
      id: cache      
      with:
       path: ~/.terraform.d/plugins/checkov1 # path to Checkov installation directory
       key: ${{ runner.os }}-checkov1
       
    - name: Install Checkov
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          pip install checkov
    - uses: actions/cache/save@v3
      with:
       path: ~/.terraform.d/plugins/checkov1 # path to Checkov installation directory
       key: ${{ runner.os }}-checkov1
