name: GitHub Pages

on:
  push:
    branches:
    - main
    - feature
    - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Concurrent Runs
      id: concurrentruns
      uses: azure/actions/concurrent-runs@v2.3.0
      with:
          check_concurrency: true
          max_concurrent_runs: 1
          context: ${{ github.workflow }}
          sha: ${{ github.sha }}    
    - name: Checkout
      uses: actions/checkout@v2
    - name: dir-create
      run: |
        mkdir -p ~/.terraform.d/plugins/checkov
    - name: Check commit
      #if: github.ref == 'refs/heads/main'
      run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is $branch"
          latest_commit=$(git ls-remote origin main | awk '{print $1}')
          current_commit=$(git rev-parse HEAD)
          if [ "$latest_commit" != "$current_commit" ] && [ "$branch" == "main" ]; then
            echo "This workflow is running on an old commit."
            echo "Hello"
            exit 1
          fi
          echo "it is not old commit"
    - uses: actions/cache/restore@v3
      id: cache      
      with:
       path: ~/.cache/pip # path to Checkov installation directory
       key: ${{ runner.os }}-checkov1
       
    - name: Install Checkov
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          pip install checkov
    - uses: actions/cache/save@v3
      with:
       path: ~/.cache/pip # path to Checkov installation directory
       key: ${{ runner.os }}-checkov1
