name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dir-create
      run: |
        mkdir -p ~/.terraform.d/plugins/checkov
    - name: cache-dependencies
      uses: actions/cache@v2
      with:
       path: ~/.terraform.d/plugins/checkov # path to Checkov installation directory
       key: ${{ runner.os }}-checkov
       restore-keys: ${{ runner.os }}-checkov
    - name: Install Checkov
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
          pip install checkov
    - uses: actions/cache/save@v3
      with:
       path: ~/.terraform.d/plugins/checkov # path to Checkov installation directory
       key: ${{ runner.os }}-checkov
