on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Another Workflow
        uses: ./.github/workflows/main.yaml
        with:
          some_input: 'Hello, World!'
